#
# AppSource Dockerfile
#
# https://github.com/erheme318/dockerfiles
#

# Pull base image.
FROM erheme318/base

MAINTAINER Erkhembayar Gantulga <erheme318@gmail.com>

# Set default working directory
WORKDIR /var/www

CMD /bin/bash
